(function(){
  const F=window.FoodLab={user:null,csrf:null};
  F.escape=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  F.toast=msg=>{const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)};
  F.api=async(url,options={})=>{const opts={...options,headers:{...(options.headers||{})}};if(opts.body&&typeof opts.body!=='string'&&!(opts.body instanceof FormData)){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}if(['POST','PUT','PATCH','DELETE'].includes(opts.method)){if(!F.csrf){const r=await fetch('/api/auth/csrf');F.csrf=(await r.json()).csrf_token}opts.headers['X-CSRF-Token']=F.csrf}const res=await fetch(url,opts);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'请求失败');return data};
  F.renderCard=item=>`<a class="recipe-card" href="/recipe.html?id=${item.id}"><div class="recipe-cover">${item.cover_image?`<img src="${F.escape(item.cover_image)}" alt="${F.escape(item.title)}">`:'🍲'}</div><div class="recipe-body"><div class="recipe-meta"><span>${F.escape(item.cuisine||item.category||'食研所')}</span><span>${item.total_time||((item.prep_time||0)+(item.cook_time||0))} 分钟</span></div><h3>${F.escape(item.title)}</h3><p>${F.escape(item.description)}</p><div class="tags">${(item.tags||[]).map(t=>`<span class="tag">${F.escape(t)}</span>`).join('')}</div><div class="recipe-meta" style="margin-top:13px"><span>♡ ${item.likes_count||0}　☆ ${item.favorites_count||0}</span><span>${F.escape(item.author||'')}</span></div></div></a>`;
  F.loadUser=async()=>{try{F.user=(await F.api('/api/auth/me')).user}catch(e){F.user=null}return F.user};
  const accountStyles='.account-menu{position:relative}.account-trigger{border:0;background:var(--sand);color:var(--ink);border-radius:999px;padding:11px 22px;font:inherit;font-weight:800;cursor:pointer;white-space:nowrap}.account-dropdown{display:none;position:absolute;right:0;top:calc(100% + 10px);min-width:220px;background:var(--card);border:1px solid var(--line);border-radius:16px;padding:10px;box-shadow:var(--shadow);z-index:40}.account-menu:hover .account-dropdown,.account-menu:focus-within .account-dropdown{display:flex;flex-direction:column}.account-dropdown a,.account-dropdown button{border:0;background:transparent;color:var(--ink);text-align:left;padding:13px 15px;border-radius:10px;font:inherit;cursor:pointer}.account-dropdown a:hover,.account-dropdown button:hover{background:var(--sand);color:var(--accent)}.account-dropdown button{border-top:1px solid var(--line);margin-top:5px;padding-top:15px}';
  function shell(){
    if(!document.querySelector('#account-menu-styles')){const style=document.createElement('style');style.id='account-menu-styles';style.textContent=accountStyles;document.head.appendChild(style)}
    const header=document.querySelector('#site-header');
    if(header){header.innerHTML=`<header class="site-header"><div class="nav container"><a class="brand" href="/"><span class="brand-mark"></span><span>食研所 <small>FoodLab</small></span></a><button class="menu-btn" id="menu-btn">☰</button><nav class="nav-links" id="nav-links"><a href="/">首页</a><a href="/recipes.html">菜谱</a><a href="/categories.html">分类</a><a href="/favorites.html">收藏</a><a href="/publish.html">发布菜谱</a></nav><div class="nav-actions"><button class="icon-btn" id="theme-btn" title="切换主题">☾</button><span id="auth-slot"><a class="btn" href="/login.html">登录</a></span></div></div></header>`;document.querySelector('#menu-btn').onclick=()=>document.querySelector('#nav-links').classList.toggle('open');document.querySelector('#theme-btn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('foodlab-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('foodlab-theme')==='dark')document.body.classList.add('dark')}
    const footer=document.querySelector('#site-footer');if(footer)footer.innerHTML='<footer class="site-footer"><div class="container footer-inner"><span>食研所 FoodLab · 发现、学习、记录美食。</span><span>© 2026 FoodLab</span></div></footer>';
    F.loadUser().then(user=>{if(!user)return;const slot=document.querySelector('#auth-slot');if(!slot)return;const adminNav=user.role==='admin'?'<a class="admin-nav" href="/admin.html">后台</a>':'';document.querySelector('#nav-links').insertAdjacentHTML('beforeend',adminNav);slot.innerHTML=`<div class="account-menu"><button class="account-trigger" type="button">${F.escape(user.username)}</button><div class="account-dropdown"><a href="/profile.html?id=${user.id}">个人主页</a><a href="/my-recipes.html">我的菜谱</a><a href="/settings.html">账户设置</a><button id="account-logout" type="button">退出登录</button></div></div>`;document.querySelector('#account-logout').onclick=async()=>{await F.api('/api/auth/logout',{method:'POST'});location.href='/login.html'}});
  }
  document.addEventListener('DOMContentLoaded',shell);
})();
