(function(){
  const F=window.FoodLab={user:null,csrf:null};
  F.escape=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  F.toast=msg=>{const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)};
  F.api=async(url,options={})=>{const opts={...options,headers:{...(options.headers||{})}};if(opts.body&&typeof opts.body!=='string'&&!(opts.body instanceof FormData)){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}if(['POST','PUT','PATCH','DELETE'].includes(opts.method)){if(!F.csrf){const r=await fetch('/api/auth/csrf');F.csrf=(await r.json()).csrf_token}opts.headers['X-CSRF-Token']=F.csrf}const res=await fetch(url,opts);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'请求失败');return data};
  F.renderCard=item=>`<a class="recipe-card" href="/recipe.html?id=${item.id}"><div class="recipe-cover">${item.cover_image?`<img src="${F.escape(item.cover_image)}" alt="${F.escape(item.title)}">`:'🍲'}${item.is_featured?'<span class="editor-pick-badge"><span aria-hidden="true">✦</span> 编辑精选</span>':''}</div><div class="recipe-body"><div class="recipe-meta"><span>${F.escape(item.cuisine||item.category||'食研所')}</span><span>${item.total_time||((item.prep_time||0)+(item.cook_time||0))} 分钟</span></div><h3>${F.escape(item.title)}</h3><p>${F.escape(item.description)}</p><div class="tags">${(item.tags||[]).map(t=>`<span class="tag">${F.escape(t)}</span>`).join('')}</div><div class="recipe-meta" style="margin-top:13px"><span>♡ ${item.likes_count||0}　☆ ${item.favorites_count||0}</span><span>${F.escape(item.author||'')}</span></div></div></a>`;
  F.loadUser=async()=>{try{F.user=(await F.api('/api/auth/me')).user}catch(e){F.user=null}return F.user};
  const accountStyles='.account-menu{position:relative;width:240px}.account-trigger{display:block;width:100%;border:1px solid transparent;background:var(--sand);color:var(--ink);border-radius:999px;padding:11px 22px;font:inherit;font-weight:800;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.account-dropdown{display:none;position:absolute;right:0;top:100%;width:100%;background:var(--card);border:1px solid var(--line);border-top:0;border-radius:0 0 16px 16px;padding:10px;box-shadow:var(--shadow);z-index:40}.account-menu:hover .account-trigger,.account-menu:focus-within .account-trigger{border-radius:16px 16px 0 0}.account-menu:hover .account-dropdown,.account-menu:focus-within .account-dropdown{display:flex;flex-direction:column}.account-dropdown a,.account-dropdown button{display:flex;align-items:center;gap:12px;border:0;background:transparent;color:var(--ink);text-align:left;padding:13px 15px;border-radius:10px;font:inherit;cursor:pointer}.account-dropdown a:hover,.account-dropdown button:hover{background:var(--sand);color:var(--accent)}.account-dropdown button{border-top:1px solid var(--line);border-radius:0 0 10px 10px;margin-top:5px;padding-top:15px}.account-item-icon{display:inline-flex;width:20px;height:20px;align-items:center;justify-content:center;color:var(--muted);flex:0 0 20px}.account-item-icon svg{width:19px;height:19px}@media(max-width:600px){.account-menu{width:190px}.account-trigger{padding-left:14px;padding-right:14px}}';
  const accountIcons={profile:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M4.5 20c.8-3.3 3.3-5 7.5-5s6.7 1.7 7.5 5"/></svg>',recipes:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M5 4.5h10a3 3 0 0 1 3 3V20H8a3 3 0 0 1-3-3V4.5Z"/><path d="M8 4.5v12a3 3 0 0 0 3 3M9 9h6M9 12h6"/></svg>',settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 8.97 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15 1.7 1.7 0 0 0 3.08 14H3v-4h.08A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88L4.2 7.06l2.83-2.83.06.06A1.7 1.7 0 0 0 8.97 4.6 1.7 1.7 0 0 0 10 3.08V3h4v.08A1.7 1.7 0 0 0 15.03 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9 1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15z"/></svg>',logout:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M10 17l5-5-5-5M15 12H3"/><path d="M21 19V5a2 2 0 0 0-2-2h-6"/></svg>'};
  function shell(){
    if(!document.querySelector('#account-menu-styles')){const style=document.createElement('style');style.id='account-menu-styles';style.textContent=accountStyles;document.head.appendChild(style)}
    const header=document.querySelector('#site-header');
    if(header){header.innerHTML=`<header class="site-header"><div class="nav container"><a class="brand" href="/"><span class="brand-mark"></span><span>食研所 <small>FoodLab</small></span></a><button class="menu-btn" id="menu-btn">☰</button><nav class="nav-links" id="nav-links"><a href="/">首页</a><a href="/recipes.html">菜谱</a><a href="/categories.html">分类</a><a href="/favorites.html">收藏</a><a href="/publish.html">发布菜谱</a></nav><div class="nav-actions"><button class="icon-btn" id="theme-btn" title="切换主题">☾</button><span id="auth-slot"><a class="btn" href="/login.html">登录</a></span></div></div></header>`;document.querySelector('#menu-btn').onclick=()=>document.querySelector('#nav-links').classList.toggle('open');document.querySelector('#theme-btn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('foodlab-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('foodlab-theme')==='dark')document.body.classList.add('dark')}
    const footer=document.querySelector('#site-footer');if(footer)footer.innerHTML='<footer class="site-footer"><div class="container footer-inner"><span>食研所 FoodLab · 发现、学习、记录美食。</span><span>© 2026 FoodLab</span></div></footer>';
    F.loadUser().then(user=>{if(!user)return;const slot=document.querySelector('#auth-slot');if(!slot)return;const adminNav=user.role==='admin'?'<a class="admin-nav" href="/admin.html">后台</a>':'';document.querySelector('#nav-links').insertAdjacentHTML('beforeend',adminNav);slot.innerHTML=`<div class="account-menu"><button class="account-trigger" type="button">${F.escape(user.username)}</button><div class="account-dropdown"><a href="/profile.html?id=${user.id}"><span class="account-item-icon">${accountIcons.profile}</span><span>个人主页</span></a><a href="/my-recipes.html"><span class="account-item-icon">${accountIcons.recipes}</span><span>我的菜谱</span></a><a href="/settings.html"><span class="account-item-icon">${accountIcons.settings}</span><span>账户设置</span></a><button id="account-logout" type="button"><span class="account-item-icon">${accountIcons.logout}</span><span>退出登录</span></button></div></div>`;document.querySelector('#account-logout').onclick=async()=>{await F.api('/api/auth/logout',{method:'POST'});location.href='/login.html'}});
  }
  document.addEventListener('DOMContentLoaded',shell);
})();
