document.addEventListener('DOMContentLoaded', async () => {
  const id = new URLSearchParams(location.search).get('id');
  try {
    const me = await FoodLab.loadUser(); const uid = id || (me && me.id); if (!uid) throw Error('请先登录');
    const d = await FoodLab.api('/api/users/' + uid); const own = me && String(me.id) === String(uid);
    const recipeData = own ? await FoodLab.api('/api/users/me/recipes') : { items: d.recipes }; const recipes = (recipeData.items || []).map(item => ({...item, author: d.user.username, author_avatar: d.user.avatar_url}));
    document.querySelector('#profile-page').innerHTML = `<section class="profile-hero panel"><div class="profile-avatar">${d.user.avatar_url ? `<img src="${FoodLab.escape(d.user.avatar_url)}" alt="${FoodLab.escape(d.user.username)}">` : '<span aria-hidden="true">♙</span>'}</div><div class="profile-copy"><h1>${FoodLab.escape(d.user.username)}</h1><p class="muted">${FoodLab.escape(d.user.bio || '这个人还没有写个人介绍。')}</p><div class="tags profile-interests">${(d.user.interests || []).map(t => `<span class="tag">${FoodLab.escape(t)}</span>`).join('') || '<span class="muted">还没有设置兴趣标签</span>'}</div><div class="stats"><span>发布 ${d.counts.recipes}</span><span id="profile-followers">粉丝 ${d.user.followers || 0}</span><span>获赞 ${d.counts.likes}</span></div>${!own && me ? `<div class="profile-social-actions"><button class="btn ${d.user.is_following ? 'secondary' : ''}" id="profile-follow">${d.user.is_following ? '已关注' : '关注'}</button></div>` : ''}</div></section><div id="my-recipes" class="section-head" style="margin-top:40px"><h2>${own ? '我的菜谱' : '公开菜谱'}</h2></div><div class="grid">${recipes.filter(item => item.status === 'published' || !own).map(item => FoodLab.renderCard(item)).join('') || '<div class="empty">还没有已发布菜谱。</div>'}</div>`;
    const follow = document.querySelector('#profile-follow');
    if (follow) follow.onclick = async () => { try { const result = await FoodLab.api('/api/users/' + uid + '/follow', {method: 'POST'}); d.user.is_following = result.active; d.user.followers = result.count; follow.textContent = result.active ? '已关注' : '关注'; follow.classList.toggle('secondary', result.active); document.querySelector('#profile-followers').textContent = `粉丝 ${result.count}`; } catch (error) { FoodLab.toast(error.message); } };
  } catch (e) { FoodLab.toast(e.message); setTimeout(() => location.href = '/login.html', 800); }
});
